config/routes.rb
Mongrallery::Application.routes.draw do

  root :to => 'pages#index'
  devise_for :users

  # - Resources - #
  resources :pictures
  resources :albums
end

app/models/album.rb
class Album < ActiveRecord::Base
  # - Default Scope - #
  default_scope :order => 'name ASC'

  # - Scopes - #
  scope :public, where(:public => true)

  # - Relationships - #
  has_many :pictures

  # - Validations - #
  validates_presence_of :name

  # - Instance Methods - #
  def is_public?
    public?
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  # - Relationships - #
  belongs_to :album

  # - Validations - #
  validates_presence_of :pic

  # - Scopes - #
  scope :orphan, where(:album_id => nil)
  scope :public_pics, joins(:album).where('albums.public = ?', true)

  # - Callbacks - #
  before_create :generate_slug

  # - CarrierWave - #
  mount_uploader :pic, PictureUploader

  # - Mass-assignment protected attributes
  attr_protected :slug

  # - Instance Methods - #
  def is_orphan?
    album_id.blank?
  end

  def is_public?
    album ? album.is_public? : true
  end

  private

    def generate_slug
      self.slug = Digest::MD5.hexdigest Time.now.to_i.to_s
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  # - Validations - #
  validates_presence_of :name

  # - Instance Methods - #
  def is_admin?
    admin
  end
end

app/controllers/albums_controller.rb
class AlbumsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authorize!, :except => [:index, :show]

  def show
    @album = Album.find params[:id]
    unless user_signed_in?
      not_found unless @album.is_public?
    end
  end

  protected
    def collection
      if user_signed_in?
        super
      else
        @albums ||= Album.public
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  respond_to :html
  helper_method :current_admin?

  def current_admin?
    current_user.try :is_admin?
  end

  def authorize!
    unless current_admin?
      redirect_to root_path, :alert => 'Access restricted.'
    end
  end

  def not_found
    render :file => "#{Rails.root}/public/404", :formats => [:html], :layout => false, :status => :not_found
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < InheritedResources::Base
  before_filter :authorize!,  :except => [:index, :show]
  before_filter :load_albums, :except => [:index, :show, :destroy]

  def show
    @picture = Picture.find params[:id]
    unless user_signed_in?
      not_found unless @picture.is_public?
    end
  end

  protected

    def collection
      if user_signed_in?
        super
      else
        @pictures = Picture.public_pics
      end
    end

    def load_albums
      @albums = Album.all
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def album_cover(album)
    image = image_path 'icon-folder.png'
    image = album.pictures.first.pic.url(:thumb) if album.pictures.any?
    image_tag image, :size => '120x160'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_links
    content_tag :p, :class => 'session navbar-text pull-right' do
      if user_signed_in?
        raw(
          link_to(current_user.name, '#') +
          ' | ' +
          link_to('Logout', destroy_user_session_path)
        )
      else
        link_to 'Login', new_user_session_path
      end
    end
  end

  def flash_messages
    {
      :alert   => 'alert',
      :notice  => 'alert alert-success',
      :error   => 'alert alert-error',
      :success => 'alert alert-success',
      :info    => 'alert alert-info'
    }.map do |key, val|
      content_tag :div, flash[key], :class => val if flash[key]
    end.join.html_safe
  end

  def new_link(url, text = 'New', _options = {})
    options = {
      :class => 'btn btn-small'
    }.merge _options
    link_to url, options do
      raw(
        content_tag(:span, '', :class => get_black_icon_class(:new)) +
        content_tag(:span, text)
      )
    end
  end

  def back_link(url, text = 'Back', _options = {})
    url ||= :back
    options = { :class => 'btn btn-small' }.merge _options
    link_to url, options do
      raw(
        content_tag(:span, '', :class => get_black_icon_class(:back)) +
        content_tag(:span, text)
      )
    end
  end

  def show_link(url, _options = {})
    options = {}.merge _options
  end

  def edit_link(url, text = 'Edit', _options = {})
    options = { :class => 'btn btn-small btn-inverse' }.merge _options
    link_to url, options do
      raw(
        content_tag(:span, '', :class => get_white_icon_class(:edit)) +
        content_tag(:span, text)
      )
    end
  end

  def destroy_link(url, text = 'Destroy', _options = {})
    options = {
      :class   => 'btn btn-small btn-danger',
      :method  => :delete,
      :confirm => 'Are you sure?'
    }.merge _options
    link_to url, options do
      raw(
        content_tag(:span, '', :class => get_white_icon_class(:destroy)) +
        content_tag(:span, text)
      )
    end
  end

  private

    def get_white_icon_class(icon)
      "iconfix icon-white #{get_icon_class icon}"
    end

    def get_black_icon_class(icon)
      "iconfix #{get_icon_class icon}"
    end

    def get_icon_class(icon)
      case icon
      when :new_picture
        'icon-picture'
      when :edit
        'icon-edit'
      when :destroy
        'icon-trash'
      when :back
        'icon-circle-arrow-left'
      when :new
        'icon-file'
      else
        'icon-ban-circle'
      end
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def picture_caption(picture)
    picture.caption? ? picture.caption : 'No caption'
  end

  def new_picture_link
    link_to new_picture_path, :class => 'btn btn-small' do
      raw(
        content_tag(:span, '', :class => get_black_icon_class(:new_picture)) +
        content_tag(:span, 'New Picture')
      )
    end
  end
end

app/views/albums/_form.html.slim
= form_for @album do |f|
  - if @album.errors.any?
    #error_explanation
      h2 = "#{pluralize(@album.errors.count, "error")} prohibited this album from being saved:"
      ul
        - @album.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name

  .field
    = f.label :public
    = f.select :public, [true, false]

  .field
    = f.label :description
    = f.text_area :description, :rows => 3

  .form-actions = f.submit 'Save', :class => 'btn btn-primary'

app/views/albums/edit.html.slim
h1 Editing album

== render 'form'

= link_to 'Show', @album
'|
= link_to 'Back', albums_path

app/views/albums/index.html.slim
ul.breadcrumb
  li
    = link_to 'Home', root_path
    span.divider >
  li Albums

- if current_admin?
  p.pull-right = new_link new_album_path, 'New Album'

.clearfix

- if @albums.any?
  ul.thumbnails.albums
    - @albums.each do |album|
      li.span3.image
        .thumbnail
          = link_to album_cover(album), album
          .caption
            p
              i.name = album.name
            - if current_admin?
              = edit_link(edit_album_path(album))
              = destroy_link(album, 'Destroy', :class => 'btn btn-small btn-danger pull-right')

app/views/albums/new.html.slim
h1 New Album

== render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.slim
ul.breadcrumb
  li
    = link_to 'Home', root_path
    span.divider >
  li
    = link_to 'Albums', albums_path
    span.divider >
  li = @album.name

p.pull-right
  - if current_admin?
    = edit_link edit_album_path @album
    = destroy_link @album, 'Destroy', :confirm => 'Are you sure you want to delete this album? This will also delete all its pictures?'
  = back_link albums_path

.clearfix

.well
  i = @album.description

- if @album.pictures.any?
  ul.thumbnails.pictures = render @album.pictures

app/views/layouts/application.html.slim
doctype 5
html
  head
    title Mongrallery
    = csrf_meta_tag
    / Le styles
    = stylesheet_link_tag 'application'

    / Le javascripts
    = javascript_include_tag 'application'
    = yield :head

  body class=controller_name
    / Top Navigation bar
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          div           = link_to 'Mongrallery', root_path, :class => 'brand'
          .nav-collapse = render 'shared/topbar'
          .pull-right   = session_links

    .container
      / Body content
      = flash_messages
      = yield
      footer
        p &copy; mongrelion 2012

app/views/pages/index.html.slim
ul.breadcrumb
  li
    ' Home

h1 Pages#index
p Find me in app/views/pages/index.html.slim

app/views/pictures/_form.html.slim
= form_for @picture do |f|
  - if @picture.errors.any?
    #error_explanation
      h2 = "#{pluralize(@picture.errors.count, "error")} prohibited this picture from being saved:"
      ul
        - @picture.errors.full_messages.each do |message|
          li = message

  - if 'new' == action_name
    .field
      - if @picture.pic?
        = image_tag @picture.pic_url
      = f.label :pic, 'Picture'
      = f.file_field :pic
      = f.hidden_field :pic_cache

  .field
    = f.label :album_id
    = f.collection_select :album_id, @albums, :id, :name, :include_blank => true

  .field
    = f.label :caption
    = f.text_area :caption, :rows => 3
  .form-actions = f.submit 'Save', :class => 'btn btn-primary'

app/views/pictures/_picture.html.slim
li.span3.image
  = hidden_field_tag :title, picture_caption(picture)
  .thumbnail
    = link_to image_tag(picture.pic.url(:thumb), :size => '120x160'), picture, :title => picture_caption(picture)
    - if current_admin?
      .caption
        = edit_link(edit_picture_path(picture))
        = destroy_link(picture, 'Destroy', :class => 'btn btn-small btn-danger pull-right')

app/views/pictures/edit.html.slim
h1 Editing picture

== render 'form'

= link_to 'Show', @picture
'|
= link_to 'Back', pictures_path

app/views/pictures/index.html.slim
ul.breadcrumb
  li
    = link_to 'Home', root_path
    span.divider >

  li Pictures

- if current_admin?
  .pull-right = new_picture_link

.clearfix

- if @pictures.any?
  ul.thumbnails.pictures = render @pictures

app/views/pictures/new.html.slim
h1 New picture

== render 'form'

= link_to 'Back', pictures_path

app/views/pictures/show.html.slim
ul.breadcrumb
  li
    = link_to 'Home', root_path
    span.divider >

  li
    = link_to 'Pictures', pictures_path
    span.divider >

  li = @picture.id

.well
  i = picture_caption @picture
  - if @picture.album
    p = link_to @picture.album.name, @picture.album

p = link_to image_tag(@picture.pic.url), @picture.pic.url


- if current_admin?
  = edit_link edit_picture_path(@picture)
  = destroy_link @picture, 'Destroy'
= back_link pictures_path

app/views/shared/_topbar.html.slim
ul.nav.menu
  li = link_to 'Albums', albums_path
  li = link_to 'Pictures', pictures_path
  - if current_admin?
    li = link_to new_picture_path do
      b New Picture